- .github/scripts/integration-test.sh
- .github/workflows/pull-request.yml
- BasisTheoryElements/Sources/BasisTheoryElements/BasisTheoryElements.swift
- waiting on Basis-Theory/basistheory-ios-example#4
- waiting on Basis-Theory/basistheory-ios-example#5
- adds application type check on tokenize call
> feat: adds application type check on tokenize call

- BasisTheoryElements/Sources/BasisTheoryElements/BaseElement.swift
- BasisTheoryElements/Sources/BasisTheoryElements/CardVerificationCodeElementUITextField.swift
- BasisTheoryElements/Sources/BasisTheoryElements/TextElementUITextField.swift
- Adds input masking w/ same behavior as Elements web to the TextElement
> feat: add input mask to text element

- .github/workflows/pull-request.yml
- .github/workflows/release.yml
- BasisTheoryElements.podspec
- BasisTheoryElements/Sources/BasisTheoryElements/CreateToken.swift
- LICENSE
- Package.resolved
- Package.swift
> fix: releases to CocoaPods

- BasisTheoryElements.podspec
- changes source files. releases to CocoaPods
> fix: changes source files. releases to CocoaPods

- BasisTheoryElements/Sources/BasisTheoryElements/BaseElement.swift
- BasisTheoryElements/Sources/BasisTheoryElements/BasisTheoryElements.swift
- BasisTheoryElements/Sources/BasisTheoryElements/CardExpirationDateUITextField.swift
- BasisTheoryElements/Sources/BasisTheoryElements/TextElementUITextField.swift
- IntegrationTester/UnitTests/CardExpirationDateUITextFieldTests.swift
- IntegrationTester/UnitTests/CardNumberUITextFieldTests.swift
-This is a PR to throw an invalid input error before tokenization if the input is invalid (invalid card number, invalid expiration date)
> Throw an error if input is invalid before tokenization

- BasisTheoryElements/README.md
- Adds a newline to trigger release to 1.0 bump
> feat: bump to 1.0

- BasisTheoryElements/Sources/BasisTheoryElements/BasisTheoryElements.swift
- IntegrationTester/IntegrationTester.xcodeproj/project.pbxproj
- IntegrationTester/IntegrationTester/SplitCardElementsViewController.swift
- IntegrationTester/IntegrationTester/TextElementUITextFieldViewController.swift
- IntegrationTester/UnitTests/ElementServiceTests.swift
- README.md
- fixes issue where we fail to retrieve an app by api key
> fix: fixes issue where we fail to retrieve an app by api key

- .github/workflows/pull-request.yml
> chore: adds dependency check

- IntegrationTester/IntegrationTester/AppDelegate.swift
- IntegrationTester/IntegrationTester/SplitCardElementsViewController.swift
- IntegrationTester/IntegrationTester/TextElementUITextFieldViewController.swift
- README.md
- updates README for clearer examples
> chore: updates README for clearer examples

- BasisTheoryElements/Sources/BasisTheoryElements/BasisTheoryElements.swift
- IntegrationTester/UnitTests/CardExpirationDateUITextFieldTests.swift
- IntegrationTester/UnitTests/ProxyServiceTests.swift
- README.md
- removing application type check on proxy call
> fix: removing application type check on proxy call

- BasisTheoryElements/Sources/BasisTheoryElements/CardNumberElementUITextField.swift
- BasisTheoryElements/Sources/BasisTheoryElements/CardVerificationCodeUITextField.swift
- BasisTheoryElements/Sources/BasisTheoryElements/TextElementUITextField.swift
- IntegrationTester/UnitTests/CardExpirationDateUITextFieldTests.swift
- IntegrationTester/UnitTests/CardNumberUITextFieldTests.swift
- README.md
- adds BIN and last4 to textChange events
> feat: adds BIN and last4 to textChange events

- BasisTheoryElements.podspec
- BasisTheoryElements/Package.swift
- BasisTheoryElements/Sources/BasisTheoryElements/BasisTheoryElements.swift
- IntegrationTester/IntegrationTester.xcodeproj/project.pbxproj
- IntegrationTester/IntegrationTester.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- IntegrationTester/UnitTests/SessionServiceTests.swift
- Package.swift
- adds createSession service function
> feat: adds createSession service function

- BasisTheoryElements/Sources/BasisTheoryElements/BasisTheoryElements.swift
- BasisTheoryElements/Sources/BasisTheoryElements/GetTokenByIdResponse.swift
- BasisTheoryElements/Sources/BasisTheoryElements/ProxyHelpers.swift
- IntegrationTester/IntegrationTester.xcodeproj/project.pbxproj
- IntegrationTester/UnitTests/GetTokenByIdServiceTests.swift
> feat: adds getTokenById func

- BasisTheoryElements/Sources/BasisTheoryElements/CardNumberElementUITextField.swift
- fixes complete flag on card number element
> fix: fixes complete flag on card number element

- .github/scripts/integration-test.sh
- BasisTheoryElements/Sources/BasisTheoryElements/CardExpirationDateUITextField.swift
- BasisTheoryElements/Sources/BasisTheoryElements/CardNumberElementUITextField.swift
- BasisTheoryElements/Sources/BasisTheoryElements/ProxyHelpers.swift
- CONTRIBUTING.md
- IntegrationTester/Configuration.swift
- IntegrationTester/IntegrationTester.xcodeproj/project.pbxproj
- IntegrationTester/IntegrationTester/Base.lproj/Main.storyboard
- IntegrationTester/IntegrationTester/CardRevealViewController.swift
- IntegrationTester/IntegrationTester/SplitCardElementsViewController.swift
- IntegrationTester/UnitTests/GetTokenByIdServiceTests.swift
- adds end-to-end card reveal example
> chore: adds end-to-end card reveal example

- .github/scripts/integration-test.sh
- removes unnecessary env vars from script
> chore: removes unnecessary env vars from script

- BasisTheoryElements/Sources/BasisTheoryElements/CardNumberElementUITextField.swift
- IntegrationTester/IntegrationTester/CardRevealViewController.swift
- Fixes warning for `vars` that were immutable on `CardNumberElement`
> fix: fix constant variables on card number

- IntegrationTester/IntegrationTester/CardRevealViewController.swift
> chore: fixes reveal end to end

- .github/workflows/security-scan.yml
- Adds github actions workflow to run a scheduled security scan
> chore: Adds security-scan scheduled workflow

- .github/workflows/release.yml
-  adding internal deployment notifications
> chore: adding deploy notifications

- .github/workflows/release.yml
- BasisTheoryElements.podspec
- BasisTheoryElements/Package.swift
- BasisTheoryElements/Sources/BasisTheoryElements/BaseElement.swift
- BasisTheoryElements/Sources/BasisTheoryElements/BasisTheoryElements.swift
- BasisTheoryElements/Sources/BasisTheoryElements/CardExpirationDateUITextField.swift
- BasisTheoryElements/Sources/BasisTheoryElements/CardNumberElementUITextField.swift
- BasisTheoryElements/Sources/BasisTheoryElements/CardVerificationCodeUITextField.swift
- BasisTheoryElements/Sources/BasisTheoryElements/ElementEvents.swift
- BasisTheoryElements/Sources/BasisTheoryElements/ProxyHelpers.swift
- BasisTheoryElements/Sources/BasisTheoryElements/TelemetryLogging.swift
- BasisTheoryElements/Sources/BasisTheoryElements/TextElementUITextField.swift
- IntegrationTester/IntegrationTester.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Package.swift
> fix: adds DataDog logging

- .github/workflows/release.yml
- fixes script to update version number
> fix: fixes script to update version number

- .github/workflows/pull-request.yml
- .github/workflows/release.yml
- BasisTheoryElements/Sources/BasisTheoryElements/TelemetryLogging.swift
- adds BasisTheoryElements as a part of release commit
> fix: adds BasisTheoryElements as a part of release commit

- BasisTheoryElements/Sources/BasisTheoryElements/CardExpirationDateUITextField.swift
- IntegrationTester/AcceptanceTests/SplitCardElementsUITextFieldTests.swift
- Prevents insertion of months over 12 for card exp date (invalid).
> feat: prevent insertion of months > 12 for card exp date

- BasisTheoryElements/Sources/BasisTheoryElements/BasisTheoryElements.swift
- IntegrationTester/UnitTests/CardExpirationDateUITextFieldTests.swift
- IntegrationTester/UnitTests/CardNumberUITextFieldTests.swift
- IntegrationTester/UnitTests/ProxyServiceTests.swift
- Allows Elements to be passed in the body when calling the proxy service.
> feat: allow elements to be passed in proxy body

- BasisTheoryElements/Sources/BasisTheoryElements/TextElementUITextField.swift
- IntegrationTester/IntegrationTester/AppDelegate.swift
- IntegrationTester/IntegrationTester/TextElementUITextFieldViewController.swift
- IntegrationTester/UnitTests/CardExpirationDateUITextFieldTests.swift
- IntegrationTester/UnitTests/CardNumberUITextFieldTests.swift
- IntegrationTester/UnitTests/ElementUITextFieldTests.swift
- IntegrationTester/UnitTests/GetTokenByIdServiceTests.swift
- IntegrationTester/UnitTests/ProxyServiceTests.swift
- IntegrationTester/UnitTests/SessionServiceTests.swift
- IntegrationTester/UnitTests/TextElementUITextFieldTests.swift
- IntegrationTester/UnitTests/TokenizeAndCreateTokenServiceTests.swift
- adds regex validation on text element
> feat: adds regex validation on text element

- BasisTheoryElements/Sources/BasisTheoryElements/BasisTheoryUIViewController.swift
- BasisTheoryElements/Sources/BasisTheoryElements/TextElementUITextField.swift
- IntegrationTester/AcceptanceTests/UITextFieldDelegateTests.swift
- IntegrationTester/IntegrationTester.xcodeproj/project.pbxproj
- IntegrationTester/IntegrationTester/Base.lproj/Main.storyboard
- IntegrationTester/IntegrationTester/FailingDelegateViewController.swift
- IntegrationTester/IntegrationTester/SucceedingDelegateViewController.swift
- IntegrationTester/IntegrationTester/TextElementUITextFieldViewController.swift
- adds BasisTheoryUIViewController class
> feat: adds BasisTheoryUIViewController class

- .github/workflows/release.yml
- releasing to CocoaPods (no changes)
> fix: releasing to CocoaPods (no changes)

- BasisTheoryElements/Sources/BasisTheoryElements/CardVerificationCodeUITextField.swift
- Add `isComplete` calculation at time of CVC event - prevent possible issue when tokenizing
> fix: add isComplete calculation to cvc event

- BasisTheoryElements/Sources/BasisTheoryElements/BasisTheoryElements.swift
- BasisTheoryElements/Sources/BasisTheoryElements/JSON.swift
- BasisTheoryElements/Sources/BasisTheoryElements/ProxyHelpers.swift
- IntegrationTester/Configuration.swift
- IntegrationTester/IntegrationTester.xcodeproj/project.pbxproj
- IntegrationTester/IntegrationTester/Base.lproj/Main.storyboard
- IntegrationTester/IntegrationTester/RawProxyResponseViewController.swift
- IntegrationTester/UnitTests/ProxyServiceTests.swift
- Package.resolved
- feat: exposing raw proxy response
- [] Not Applicable
> feat: exposes raw proxy response

- BasisTheoryElements/Package.swift
- BasisTheoryElements/Sources/BasisTheoryElements/BasisTheoryElements.swift
- BasisTheoryElements/Sources/BasisTheoryElements/CardExpirationDateUITextField.swift
- BasisTheoryElements/Sources/BasisTheoryElements/CardNumberElementUITextField.swift
- BasisTheoryElements/Sources/BasisTheoryElements/CardVerificationCodeUITextField.swift
- BasisTheoryElements/Sources/BasisTheoryElements/HttpClientHelpers.swift
- BasisTheoryElements/Sources/BasisTheoryElements/ProxyHelpers.swift
- BasisTheoryElements/Sources/BasisTheoryElements/TelemetryLogging.swift
- BasisTheoryElements/Sources/BasisTheoryElements/TextElementUITextField.swift
- IntegrationTester/IntegrationTester.xcodeproj/project.pbxproj
- IntegrationTester/IntegrationTester.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- IntegrationTester/UnitTests/HttpClientTests.swift
- Package.swift
- adds http client for sending element values to third parties
> feat: adds http client for sending element values to third parties

- BasisTheoryElements/Sources/BasisTheoryElements/CardExpirationDateUITextField.swift
- IntegrationTester/UnitTests/CardExpirationDateUITextFieldTests.swift
> feat: adds date formatter

- BasisTheoryElements/Sources/BasisTheoryElements/HttpClientHelpers.swift
- IntegrationTester/IntegrationTester.xcodeproj/project.pbxproj
- IntegrationTester/IntegrationTester/Base.lproj/Main.storyboard
- IntegrationTester/IntegrationTester/HttpClientViewController.swift
- IntegrationTester/UnitTests/CardExpirationDateUITextFieldTests.swift
- IntegrationTester/UnitTests/HttpClientTests.swift
- feat: adds support for `x-www-form-urlencoded`
- adds example for creating a card in stripe
> feat: adds support for `x-www-form-urlencoded`

- BasisTheoryElements.podspec
- BasisTheoryElements/Package.swift
- Package.swift
- Allow our package to use any DataDog version resolved by customers between `1.16.0` and `2.0.0`
> feat: loose dd version requirement

- BasisTheoryElements/Sources/BasisTheoryElements/BaseElement.swift
- BasisTheoryElements/Sources/BasisTheoryElements/BasisTheoryElements.swift
- BasisTheoryElements/Sources/BasisTheoryElements/BtDatadogLogger.swift
- BasisTheoryElements/Sources/BasisTheoryElements/CardExpirationDateUITextField.swift
- BasisTheoryElements/Sources/BasisTheoryElements/CardNumberElementUITextField.swift
- BasisTheoryElements/Sources/BasisTheoryElements/CardVerificationCodeUITextField.swift
- BasisTheoryElements/Sources/BasisTheoryElements/ElementEvents.swift
- BasisTheoryElements/Sources/BasisTheoryElements/HttpClientHelpers.swift
- BasisTheoryElements/Sources/BasisTheoryElements/ProxyHelpers.swift
- BasisTheoryElements/Sources/BasisTheoryElements/TelemetryLogging.swift
- BasisTheoryElements/Sources/BasisTheoryElements/TextElementUITextField.swift
> feat: restores logging

- BasisTheoryElements/Sources/BasisTheoryElements/CardNumberElementUITextField.swift
- IntegrationTester/UnitTests/CardExpirationDateUITextFieldTests.swift
- Move card brand validation to happen after previous mask is applied.
- Fix bug where tests for expiration dates would fail in December
> fix: fix card validation being applied before masking

- BasisTheoryElements/Sources/BasisTheoryElements/BaseElement.swift
- BasisTheoryElements/Sources/BasisTheoryElements/CardBrand.swift
- BasisTheoryElements/Sources/BasisTheoryElements/CardNumberElementUITextField.swift
- IntegrationTester/AcceptanceTests/SplitCardElementsUITextFieldTests.swift
- IntegrationTester/IntegrationTester.xcodeproj/project.pbxproj
- IntegrationTester/UnitTests/CardBrandTests.swift
- feat: adds custom bin validation
> feat: adds custom bin validation

- .github/workflows/pull-request.yml
- .github/workflows/release.yml
- update workflows for secrets mgmt update
> chore: update workflows for secrets mgmt update

- .github/scripts/integration-test.sh
- .github/workflows/release.yml
> ci: update release notifications

- .github/workflows/pull-request.yml
- .github/workflows/security-scan.yml
- BasisTheoryElements.podspec
- CHANGELOG.md
- README.md
> feat: renaming repo

- .github/workflows/release.yml
> ci: tag PROD environment
